
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1277/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.19.0-35-generic - aarch64
...
